### ISSUE TITLE
pip fails to install pycount

### ISSUE THREAD

**Issue by 5j9** [tsaulic/pycount#1]
```
$ pip install pycount
Collecting pycount
  Downloading pycount-0.6.17.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "...\Temp\pip-build-a2e2n2at\pycount\setup.py", line 31, in <module>
        long_description=read('README.md'),
      File "...\Temp\pip-build-a2e2n2at\pycount\setup.py", line 18, in read
        with codecs.open(os.path.join(HERE, *parts), "rb", "utf-8") as a_file:
      File "...\programs\python\python36\lib\codecs.py", line 895, in open
        file = builtins.open(filename, mode, buffering)
    FileNotFoundError: [Errno 2] No such file or directory: '...\\Temp\\pip-build-a2e2n2at\\pycount\\README.md'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in ...\Temp\pip-build-a2e2n2at\pycount\
```

**Comment by tsaulic** [comment]
Hello, thanks for reporting this.
Been able to reproduce. I've now fixed the problem in the new version... I was missing a MANIFEST.in file with the non-code includes apparently. It should work now.
